### ISSUE TITLE
M3 Documentation Umbrella

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#1278]
## General
Update documentation overviews and consider starting an FAQ #1277
Add documentation versioning #1152

## Operational Guides
- [X] Bootstrapping
- [X] Topology / Placement
- [x] Namespace Changes
- [x] Topology / Placement changes (node adds/removes/replaces)
- [ ] Configuring aggregated namespaces
- [ ] Recommending configured alerts (including one for issues like #960)
- [ ] High availability vs high consistency configurations
- [ ] Picking number of shards / blocksize based on retention etc
- [x] System configuration (kernel settings and such). Some inspiration from other dbs:
    - https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html
    - https://docs.mongodb.com/manual/administration/production-checklist-operations/#linux
    - https://www.elastic.co/guide/en/elasticsearch/guide/current/_file_descriptors_and_mmap.html
- [ ] Seed node management

## Tutorials
Add better documentation for setting up up a single m3db node #457

## Bugs
Invalid openapi docs #1274

**Comment by schallert** [comment]
To expand on the "seed node management" task: operating seed nodes requires some extra care because you have to manage an m3db cluster _and_ an etcd cluster in one. If you wipe the data on a seed node, you'll have to use `etcdctl` or the etcd API to remove the old member and re-add it.

We should write some documentation that expands on the implications of coupling m3db's lifetime with etcd, and talks about how to operate etcd in the context of m3db.
