### ISSUE TITLE
Poor performance for tag completion endpoints

### ISSUE THREAD

**Issue by arnikola** [m3db/m3#1453]
Users have been reporting poor performance when hitting any of the tag completion endpoints in m3query and m3coordinator; these requests are slow and often OOM clusters. 

The root cause of this is that the M3DB client does not expose an endpoint to list available tag name/pairs, and m3query must make do by fetching all IDs matching the request then deduping them. Essentially, this means that trying to get a list of available tags pulls every single series into memory within M3DB, returns it up to Query, and then processed to return the list of valid tags. 

This issue affects Grafana templating, Graphite `find` endpoints, and any tag completion features.

This issue will track work to build and expose a tag completion endpoint in M3DB which will greatly increase the performance, and reduce the memory overhead required to perform these requests.

Most of these are being done independently but there's a few dependancies which will be called out: 

- [x] Hook up the new endpoints m3query side (#1481)
- [x] Add Thrift RPC types for the client (#1460)
- [x] Add the endpoint on the client session side (#1483)
- [x] Push down a single `Results` object into the query and merge all individual block postings lists into that, rather than allocating a Results per block then merging them together (#1474) 
- [x] Build the logic on the index itself (#1463) 
    - [x] (this will be refactored to look more similar to #1474 above)

**Comment by evanhuang996** [comment]
How is the progress?

**Comment by arnikola** [comment]
Hey, will add a checklist here for slightly better tracking. Most of these are being done independently but there's a few dependancies which will be called out: 

[] Hook up the new endpoints m3query side (#1481)
[] Add Thrift RPC types for the client (#1460)
[] Add the endpoint on the client session side (#1483)
[] Push down a single `Results` object into the query and merge all individual block postings lists into that, rather than allocating a Results per block then merging them together (#1474) 
[] Build the logic on the index itself (#1463) (this will be refactored to look more similar to #1474 above)

**Comment by arnikola** [comment]
Resolved in 0.8.0 :+1:
