### ISSUE TITLE
Embedded Reverse Index Followups

### ISSUE THREAD

**Issue by prateek** [m3db/m3#585]
Parent issue to track all follow ups for the current version of the embedded index. 

## Limitations 
- [ ] Decouple index & time-series data bootstrapping 

## Bugs
- [ ] FetchTagged during/after topology changes #550
- [ ] Async queuing issues 
- [ ] queue draining on Close
- [ ] Sync write path error return

### Storage 
- [ ] Stored fields for indexed series 
- [ ] Updating indexed series 
- [ ] Deleting indexed series 
### Query 
- [ ] Aggregation queries (eg search endpoint in grafana)
- [ ] Multi queries in a single FetchTagged RPC - needed for multi fetch expressions
- [ ] Filter/Query cache
- [ ] Pagination 
- [ ] Scroll
### Performance 
- [ ] Segment compaction
- [ ] Optimised segments: FST/Trigram/etc
- [ ] Optimised postings lists implementations
- [ ] `uint64` posting.ID

## Observability
- [ ] FetchTagged Tracing Information #553

## Misc
- [x] Parallelise query execution over index.Blocks 
- [ ] Push down query limits when executing over a list of segments.
- [ ] Pooling of a variety of allocs in m3db around the indexing system: Batch/[]Doc during writes, []Readers during queries. 
- [ ] Create a mutable segment allocator (so that different places - e.g. bootstrapper) can use segments more easily 
- [ ] Peers bootstrapper should cache read series from bootstrapping data so it does not need to go network to fetch metadata for any time ranges that series were already fetched
- [ ] Commit log bootstrapper should cache read series from bootstrapping data so it does not need to go and re-read commit logs to fetch metadata for any time ranges that series were already read
