### ISSUE TITLE
M3DB Operational Guides

### ISSUE THREAD

**Issue by richardartoul** [m3db/m3#964]
- [X] Bootstrapping
- [X] Topology / Placement
- [x] Namespace Changes
- [x] Topology / Placement changes (node adds/removes/replaces)
- [ ] Configuring aggregated namespaces
- [ ] Recommending configured alerts (including one for issues like #960)
- [ ] High availability vs high consistency configurations
- [ ] System configuration (kernel settings and such). Some inspiration from other dbs:
    - https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html
    - https://docs.mongodb.com/manual/administration/production-checklist-operations/#linux
    - https://www.elastic.co/guide/en/elasticsearch/guide/current/_file_descriptors_and_mmap.html

**Comment by matejzero** [comment]
A few things I would like to know when building a cluster:
- how many shards do I need for my cluster
- calculating right blocksize vs retention period
- explanation of config options when creating a new namespace

**Comment by prateek** [comment]
Some inspiration from other dbs:
- https://www.cockroachlabs.com/docs/stable/recommended-production-settings.html
- https://docs.mongodb.com/manual/administration/production-checklist-operations/#linux
- https://www.elastic.co/guide/en/elasticsearch/guide/current/_file_descriptors_and_mmap.html

**Comment by prateek** [comment]
One more thing to add: we should expose a RPC endpoint on the node and cluster services to expose system configuration. And make topology/namespace initialise endpoints query the nodes in the cluster to ensure the values are sane before making modifications.

**Comment by richardartoul** [comment]
Namespace operational guide: #995

**Comment by richardartoul** [comment]
Placement change operational guide: #998

**Comment by richardartoul** [comment]
Closing in favor of master issue: #1278
